/**
 * DoMeta API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AddPropertyToValueObjectModel } from '../model/addPropertyToValueObjectModel';
import { RegisterValueObjectModel } from '../model/registerValueObjectModel';
import { ValueObjectModel } from '../model/valueObjectModel';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ValueObjectsService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param boundedContextId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiBcBoundedContextIdValueObjectsGet(boundedContextId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<ValueObjectModel>>;
    public apiBcBoundedContextIdValueObjectsGet(boundedContextId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ValueObjectModel>>>;
    public apiBcBoundedContextIdValueObjectsGet(boundedContextId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ValueObjectModel>>>;
    public apiBcBoundedContextIdValueObjectsGet(boundedContextId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (boundedContextId === null || boundedContextId === undefined) {
            throw new Error('Required parameter boundedContextId was null or undefined when calling apiBcBoundedContextIdValueObjectsGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ValueObjectModel>>('get',`${this.basePath}/api/bc/${encodeURIComponent(String(boundedContextId))}/valueObjects`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param boundedContextId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiBcBoundedContextIdValueObjectsIdPropertiesPost(id: string, boundedContextId: string, body?: AddPropertyToValueObjectModel, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiBcBoundedContextIdValueObjectsIdPropertiesPost(id: string, boundedContextId: string, body?: AddPropertyToValueObjectModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiBcBoundedContextIdValueObjectsIdPropertiesPost(id: string, boundedContextId: string, body?: AddPropertyToValueObjectModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiBcBoundedContextIdValueObjectsIdPropertiesPost(id: string, boundedContextId: string, body?: AddPropertyToValueObjectModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiBcBoundedContextIdValueObjectsIdPropertiesPost.');
        }

        if (boundedContextId === null || boundedContextId === undefined) {
            throw new Error('Required parameter boundedContextId was null or undefined when calling apiBcBoundedContextIdValueObjectsIdPropertiesPost.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/api/bc/${encodeURIComponent(String(boundedContextId))}/valueObjects/${encodeURIComponent(String(id))}/properties`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param boundedContextId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiBcBoundedContextIdValueObjectsPost(boundedContextId: string, body?: RegisterValueObjectModel, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiBcBoundedContextIdValueObjectsPost(boundedContextId: string, body?: RegisterValueObjectModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiBcBoundedContextIdValueObjectsPost(boundedContextId: string, body?: RegisterValueObjectModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiBcBoundedContextIdValueObjectsPost(boundedContextId: string, body?: RegisterValueObjectModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (boundedContextId === null || boundedContextId === undefined) {
            throw new Error('Required parameter boundedContextId was null or undefined when calling apiBcBoundedContextIdValueObjectsPost.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/api/bc/${encodeURIComponent(String(boundedContextId))}/valueObjects`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
